### ISSUE TITLE
[ERROR] Error while loading on 1.17.1

### ISSUE THREAD

**Issue by NiniDev** [MrsDarth/Skirt#2]
Infos about the server:
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-Paper-139 (MC: 1.17.1)
[Skript] Skript Version: 2.6-beta2
[Skript] Installed Skript Addons:
[Skript]  - Skirt v1.2.3
[Skript]  - skript-yaml v1.4
[Skript]  - skDragon v0.17
[Skript]  - skript-reflect v2.2.2-dev (https://github.com/TPGamesNL/skript-reflect)
[Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
[Skript]  - SkJade v1.3.3 (https://www.github.com/Ankoki-Dev/SkJade)

https://pastebin.com/QRYm0Nkq
When I start the server I get the error.

**Comment by MrsDarth** [comment]
Skirt is only for 1.16.5 atm, i will update it to support 1.17 when skript 2.6 is stable

**Comment by NiniDev** [comment]
Okay, thanks!
