### ISSUE TITLE
Raytracing: Entities

### ISSUE THREAD

**Issue by eem50** [MrsDarth/Skirt#5]
### Hey MrsDarth,

**I'm a big fan of your Skirt addon, especially the raytracing feature. I've got two issues with it though.** 

First of all the entity detection doesn't seem to work, or I'm just doing something wrong. Here is the code I'm using:
![image](https://user-images.githubusercontent.com/96268837/146461906-34b5cd07-4c0b-42c9-b485-306fdabdaa42.png)

And here is the result I'm getting: 
![image](https://user-images.githubusercontent.com/96268837/146461311-3849e2cb-6aca-4588-8740-b2fde8ddaa0f.png) 
The problem is that it doesn't seem to hit entities, When broadcasting the raytracing result it just says hitEntity=Null though I'm clearly targeting an entity. 

My second problem is that there raytracing isn't mentioned at all in the Skirt Wiki, the only place where you can find the syntax for it is on skripthub. Some examples or a wiki page of it would be more than welcome :D

I hope you can help me with my issues :)

Greetings Eem50

**Comment by MrsDarth** [comment]
You are using the first syntax which is ray trace from living entities and this only accounts for blocks. If u want to account for entities you should use the entity ray trace or generic


edit: I’ll work on wiki one day

**Comment by eem50** [comment]
Thanks for you response :D

Currently testing generic ray trace using this code:
![afbeelding](https://user-images.githubusercontent.com/96268837/146967415-1a354a51-4911-4e16-8ab3-58d0e3d31d4c.png)
When I reload the skript it gives me no errors, however the command doesn't seem to exist. I've tested this multiple ways and generic ray trace just seems to break the skript every time... Proof: 
![afbeelding](https://user-images.githubusercontent.com/96268837/146967639-195a59fb-75a2-4498-9e26-40d60c36a8c0.png)


I also tried using entity ray trace, that one didn't break my skript but I just couldn't get a result (I'm suspecting it's broken too...)
![afbeelding](https://user-images.githubusercontent.com/96268837/146967951-29ce097e-fd26-4e6b-bcd3-4d344e2bf872.png)
Whenever I'm using it and standing south of a mob, it just says <none>. I also tried getting a 'hit entity of {_raycast::*}' but no luck either.
Also no compile errors on the second skript btw

**Comment by MrsDarth** [comment]
Are you using the pre release? I haven’t tested almost anything at all on it and can only work on it next week when I’m free

**Comment by eem50** [comment]
Thanks for the fast response.

Yes, I’m using the pre-release. I’m assuming that is the problem. Then I’ll just have patience till you have fixed it (which I hope you will). Good luck :)

**Comment by MrsDarth** [comment]
I updated the release and tested with `entity ray trace from player's eyes using forward filtering player` and works now.

**Comment by eem50** [comment]
Thanks again for helping me :D. I've worked with the entity ray trace and it works great! Skirt is truly the missing addon I need for my server. 

I also tried generic ray trace but that didn't seem to give me any response... Here the code that shows off the problem

```
command /raytracetest:
	trigger:
		broadcast " "
		set {_raycast::*} to ray trace from player
		broadcast "Default ray trace: %hit location of {_raycast::*}%"
		broadcast "Default ray trace: %hit entity of {_raycast::*}%"
		broadcast "Default ray trace: %hit block of {_raycast::*}%"	
		broadcast " "

		set {_raycast::*} to entity ray trace from player's eyes using forward filtering player
		broadcast "Entity ray trace: %hit location of {_raycast::*}%"
		broadcast "Entity ray trace: %hit entity of {_raycast::*}%"
		broadcast "Entity ray trace: %hit block of {_raycast::*}%"
		broadcast " "
		
		set {_raycast::*} to generic ray trace from player's eyes using forward filtering player
		broadcast "Generic ray trace: %hit location of {_raycast::*}%"
		broadcast "Generic ray trace: %hit entity of {_raycast::*}%"
		broadcast "Generic ray trace: %hit block of {_raycast::*}%"
```

And here the console 
![afbeelding](https://user-images.githubusercontent.com/96268837/147819304-482c8d09-2859-4fd6-9e75-bf4f82dc6e4b.png)

**Comment by MrsDarth** [comment]
my bad wrote the syntax wrong should work now

**Comment by eem50** [comment]
I tested it just 5mins ago, works great! You have no idea how much this helps me with my server :D Thanks for the help!
